### ISSUE TITLE
Data links

### ISSUE THREAD

**Issue by sr320** [jheare/Fish546-Jake#1]
Need to provide links to raw data in your notebook

**Comment by jheare** [comment]
Oh wow, I completely forgot about that. Also I've been looking for the raw data this week to throw into iplant. Can you tell me where it is on the server so I can make some links to it and start playing with it.

**Comment by jheare** [comment]
Derp! I just found it. Man I'm still running in second gear this week.

**Comment by sr320** [comment]
see https://github.com/sr320/LabDocs/blob/master/DMPseq.md
and
https://www.google.com/fusiontables/DataSource?docid=13IxnqIZ_2Xpz_HE-3YcnU_egASYz9ZlA0PYIDGLN

for future reference
