### ISSUE TITLE
Raw data info

### ISSUE THREAD

**Issue by sr320** [jheare/Fish546-Jake#2]
Your Week 1 notebook needs to have information on     
- What samples
- how libraries were made
- what type of sequencing

**Comment by jheare** [comment]
I've updated the notebook using information from your protocol to complete these requirements. I'm not exactly sure what you mean by type of sequencing other than its RAD-Sequencing.

**Comment by sr320** [comment]
Platform ie Illumina - Single End or Paired End; read length..
