### ISSUE TITLE
Links to relevant files

### ISSUE THREAD

**Issue by sr320** [jheare/Fish546-Jake#3]
For week 2 notebook link to log file should be in notebook itself.
Can run !head command to see in notebook in addition to link.

Also I suggest using headings to better organize notebooks.

**Comment by jheare** [comment]
I added the headings like you suggested. I'm having a hard time figuring out how to link from inside the ipynb file to the log file on github. I've tried using both the relative path and the URL for the file in github. Neither work once the notebook is on github.

**Comment by sr320** [comment]
one option is markdown cell

`[logfile](https://github.com/jheare/Fish546-Jake/blob/master/data/process_radtags.log)`

or

`[logfile](./data/process_radtags.log)`

and/or  code cell

`!head ./data/process_radtags.log`

or 

`!cat  ./data/process_radtags.log`

**Comment by jheare** [comment]
There's something weird going on with NBViewer. My git hub repository has the most up to date version of my notebook but the viewer is showing a cached copy of a previous version.

**Comment by jheare** [comment]
Also I've tried using the Markdown link with both the relative and URL, they don't work once its up on Github. The newest version of the notebook has the !head command in it but NBViewer isn't showing it at the moment.

**Comment by jheare** [comment]
Apparently the caching thing is a known issue with NBViewer. It should catch up in 20 minutes or so.
